<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IBM-PG02TZZN" failures="1" tests="1" name="Get" time="2.891" errors="0" timestamp="14 Oct 2023 13:58:15 GMT">
  <testcase classname="testCases.paypal.GetOrderTest" name="getOrder" time="2.878">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.paypal.GetOrderTest.getOrder(GetOrderTest.java:22)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- getOrder -->
</testsuite> <!-- Get -->
