<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="IBM-PG02TZZN" failures="6" tests="6" name="Test" time="5.987" errors="0" timestamp="14 Oct 2023 13:34:43 GMT">
  <testcase classname="testCases.paypal.CreateOrderTest" name="createOrder" time="3.209">
    <failure type="java.lang.AssertionError" message="expected [CREATED] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [CREATED] but found [null]
at testCases.paypal.CreateOrderTest.createOrder(CreateOrderTest.java:23)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- createOrder -->
  <testcase classname="testCases.paypal.CreateOrderTest" name="createOrder" time="3.26">
    <failure type="java.lang.AssertionError" message="expected [CREATED] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [CREATED] but found [null]
at testCases.paypal.CreateOrderTest.createOrder(CreateOrderTest.java:23)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- createOrder -->
  <testcase classname="testCases.paypal.CreateOrderTest" name="createOrder" time="3.274">
    <failure type="java.lang.AssertionError" message="expected [CREATED] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [CREATED] but found [null]
at testCases.paypal.CreateOrderTest.createOrder(CreateOrderTest.java:23)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- createOrder -->
  <testcase classname="testCases.paypal.CreateOrderTest" name="createOrder" time="3.398">
    <failure type="java.lang.AssertionError" message="expected [CREATED] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [CREATED] but found [null]
at testCases.paypal.CreateOrderTest.createOrder(CreateOrderTest.java:23)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- createOrder -->
  <testcase classname="testCases.paypal.CreateOrderTest" name="createOrder" time="3.461">
    <failure type="java.lang.AssertionError" message="expected [CREATED] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [CREATED] but found [null]
at testCases.paypal.CreateOrderTest.createOrder(CreateOrderTest.java:23)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- createOrder -->
  <testcase classname="testCases.paypal.GetOrderTest" name="getOrder" time="2.498">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.paypal.GetOrderTest.getOrder(GetOrderTest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getOrder -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Test -->
